### ISSUE TITLE
hs-64 example workflow has wrong bno orientation

### ISSUE THREAD

**Issue by ChucklesOnGitHub** [open-ephys/bonsai-onix1-docs#115]
In the example workflow embedded in https://open-ephys.github.io/bonsai-onix1-docs/articles/hardware/hs64/workflow.html, the configuration of the IMU orientation should be 0,0,1.

**Comment by jonnew** [comment]
The headstages (should not) allow manual specifications of the BNO orientation. Which node are you referring to? The headstage configuration or the `AutoCommutator`?

**Comment by cjsha** [comment]
yeah she's referring to `AutoCommutator`. For some reason it was 0, -1, 0 in the workflow.
