### ISSUE TITLE
Tutorial on signal processing of ephys data

### ISSUE THREAD

**Issue by ChucklesOnGitHub** [open-ephys/bonsai-onix1-docs#122]
selecting channels
ADC Rescaling
spike visualizers (vs ephys socket, reference #121 )
spike detection

- [x] #124

**Comment by cjsha** [comment]
This is an example comment for demonstrative purposes.

What is the best solution for scaling the ephys signal?

**Comment by jonnew** [comment]
This is important for real-time feedback. However, Bonsai's integrated spike detection functionality and visualizers are quite primitive and this is especially true when looking at data from very dense arrays like Neuropixels where spiking activity is best visualize using dense raster plots and thins like the OE GUI probe viewer. 

So this fact should probably be mentioned in this tutorial: spike detection and closed-loop latency will be fastest when performed in bonsai. The best visualization option without real-time feedback is the socket + OE GUI.

**Comment by ChucklesOnGitHub** [comment]
Visualization with better tools is covered in the[ ephys socket tutorial](https://github.com/open-ephys/bonsai-onix1-docs/issues/121).
As a first pass, this working with spikes tutorial is about what signal processing tools there are in Bonsai and to express the point about short closed-loop latencies, but ideally would include modules on real time spike sorting/ripple detection when such methods are available.
