### ISSUE TITLE
hs-64 tutorial edits

### ISSUE THREAD

**Issue by ChucklesOnGitHub** [open-ephys/bonsai-onix1-docs#147]
- the tutorial contains auxiliary data but those channels are not physically linked to anything on the headstage
- the imu axes are wrong, should be 0, -1, 0 for proper operation

**Comment by cjsha** [comment]
@jonnew was just explaining to me how the e-stim signal can be read back through the aux data. This will be included in the hardware guide

the imu axes have been fixed, and that fix has been deployed.

**Comment by cjsha** [comment]
Wait, I think I misread/misunderstood when I looked at this issue:

> - the imu axes are wrong, should be 0, -1, 0 for proper operation

If this is true, I believe this should be an issue in the https://github.com/open-ephys/bonsai-onix1 repo. I just did that https://github.com/open-ephys/bonsai-onix1/issues/378 and if we need to be investigated/fixed, and I'm going to close this one (we can reopen it if we need to).
