### ISSUE TITLE
basic NP1e workflow example broken

### ISSUE THREAD

**Issue by RobertoDF** [open-ephys/bonsai-onix1-docs#161]
Hi,
commit #155  has broken the example workflow workflows/hardware/np1e/np1e.bonsai 
![grafik](https://github.com/user-attachments/assets/cea8d054-c01b-4955-871d-0122b30fb7a3)

**Comment by RobertoDF** [comment]
Also I remember some earlier example was llogging the date to each saved file, how can I do that again?
Thanks!

**Comment by cjsha** [comment]
Can you clarify what you mean by this?
> I remember some earlier example was llogging the date to each saved file, how can I do that again?

**Comment by cjsha** [comment]
@RobertoDF we merged a new workflow into the docs. Can you see if it works for you?

**Comment by RobertoDF** [comment]
I meant the suffix of the file. Figured out how to do it!

**Comment by cjsha** [comment]
oh yeah. We use filecount suffixes in our example workflows bc it makes loading data easier in our examples. Not all files produced by a given data acquisition session end up having the same timestamp. 

In any case, I'm glad you figured it out and you're able to adapt the workflow to best suit your needs.

**Comment by RobertoDF** [comment]
> @RobertoDF we merged a new workflow into the docs. Can you see if it works for you?

I'll check Monday👍

**Comment by cjsha** [comment]
Ok thanks

**Comment by RobertoDF** [comment]
Confirmed, all good👍

**Comment by cjsha** [comment]
Thanks!
