### ISSUE TITLE
 Only some attributes are pulled into the auto-generated api .yaml files

### ISSUE THREAD

**Issue by cjsha** [open-ephys/bonsai-onix1-docs#29]
This needs to fix so that I can categorize properties into "Configuration Property" or "Acquisition Property" categories.

For example:

- ``[Range(0, 1000000)]`` is pulled into syntax.content for ``BeatsPerSecond``
- ``[Category(ConfigurationCategory)]`` & ``[Description(<whatever>)]`` are not pulled into syntax.content for either ``BeatsPerSecond`` or ``Enable``
![Screenshot 2024-07-25 141522](https://github.com/user-attachments/assets/0dd3becd-6d72-4b74-a4c3-d8e51fe9e005)
![Screenshot 2024-07-25 141737](https://github.com/user-attachments/assets/8efb9d48-f374-437a-8635-a9a61e9925c8)
![Screenshot 2024-07-25 141857](https://github.com/user-attachments/assets/331217d1-f4b0-43c9-9f8e-181e0b596ccd)

The relevant files for this example are: OpenEphys.Onix.ConfigureHeartbeart.yml (generated locally by ``docfx metadata`` command) and [ConfigureHeartbeart.cs](https://github.com/neurogears/onix-refactor/blob/main/OpenEphys.Onix/OpenEphys.Onix/ConfigureHeartbeat.cs)

**Comment by cjsha** [comment]
[relevant issue in the docfx repo](https://github.com/dotnet/docfx/issues/10173)

**Comment by cjsha** [comment]
After [input from the docfx people](https://github.com/dotnet/docfx/issues/10173#issuecomment-2430513568), I can pull custom attributes into the metadata. They were getting excluded because [docfx's default filter](https://github.com/dotnet/docfx/blob/af68cbdd73b803a010fd8c22ad64148bf6337a8f/src/Docfx.Dotnet/Resources/defaultfilterconfig.yml#L38-L43) excludes attributes define in `System.ComponentModel` namespace. This can be fixed by manually including the attributes we want to use in the docs in the `filter.yml` like this:

``` yaml
attributeRules:
- include: # this is necessary to pull our custom attributes into .yml metadata without disabling the docfx default filter
    uidRegex: ^System\.ComponentModel\.(CategoryAttribute|DescriptionAttribute)$
    type: Type 
```
Below is an example of a metadata file that is generated by including the above lines in the `filter.yml` file. Here you can see what I'm talking about regarding the attribute namespace. Ctrl+F the file for "attributes:" I attached a zip file because github doesn't allow attaching .yml files.
[OpenEphys.Onix1.ConfigureHeartbeat.zip](https://github.com/user-attachments/files/17497132/OpenEphys.Onix1.ConfigureHeartbeat.zip)

An alternative would be defining these attributes in another namespace, if possible. For example, it seems that the `[Range(min, max)]` attribute is defined in the Bonsai namespace so it wasn't getting filtered out. I don't know enough to know if this is worth considering. In any case, I doubt it because we should mold the docs around the code and not the other way around.

**Comment by jonnew** [comment]
This is a good one to discuss in our next technical meeting.
