### ISSUE TITLE
"Devices" header Instead of "Properties" header for hubs

### ISSUE THREAD

**Issue by cjsha** [open-ephys/bonsai-onix1-docs#46]
Look at this discussion for reference
https://github.com/open-ephys/onix-bonsai-onix1/issues/226#issuecomment-2302622396_

**Comment by cjsha** [comment]
I propose it should follow the same hierarchy as is present in Bonsai.

![image](https://github.com/user-attachments/assets/6d3328fd-5ade-4f7e-bead-18a0f25438d5)

Above is what's in Bonsai's properties panel for `NeuropixelsV1eHeadstage`
Below is a proposal for the structure for the docs for that particular headstage:

```
## Properties

### Configuration

Table with rows corresponding to:
- Name
- Port
- PortVoltage

### Devices

#### Bno055

Table with row corresponding to:
- Enable

#### NeuropixelsV1e

Table with rows corresponding to:
- Enable
- EnableLed
- GainCalibrationFile
- AdcCalibrationFile
- ProbeConfiguration
```

**Comment by bparks13** [comment]
If it is easier to automate this using attributes, Bonsai sorts these properties using the `[Category()]` attribute.
