### ISSUE TITLE
Add DataFrames to the TOC 

### ISSUE THREAD

**Issue by bparks13** [open-ephys/bonsai-onix1-docs#72]
It is very confusing to click on a data frame link (such as [AnalogInputDataFrame](https://open-ephys.github.io/onix1-bonsai-docs/api/OpenEphys.Onix1.AnalogInputDataFrame.html)) and have it open what looks like an orphaned page. There is no drop-down of the TOC on the left, and no indication of where the page is. 

These data frames are linked in a number of places, and I believe they deserve an index of some sort to show it is not a mistake for the page to be there.

**Comment by jonnew** [comment]
I agree.

**Comment by cjsha** [comment]
They're all derived from DataFrame or BufferedDataFrame with the exception of OutputClockParameters
