### ISSUE TITLE
Update README regarding lychee checks on new files

### ISSUE THREAD

**Issue by bparks13** [open-ephys/bonsai-onix1-docs#74]
When running the `lychee` link checking step locally, it can fail if new files have been created or renamed but have not been pushed to the remote repo yet.

This comes from the newly built HTML page containing a self-referential link in the **Edit this page** button, but the link it points to is hosted on Github and therefore does not exist if the newly added or renamed file has not been pushed yet. This is normal and expected behavior, and as far as I am aware cannot be filtered out to distinguish between a new local file and a previously existing remote file.

While this is not a solution, we will need to update the README to note this issue so that developers do not spend an undue amount of time trying to troubleshoot this particular issue.

There are no adverse effects on building the pages locally, everything can be tested locally without issue. This will only show up if you try to click on the **Edit this page** button in a local build, since it will go to a broken Github link. There isn't really a good use case for needing to click on that button from a local build, therefore I believe that noting this in the README will be sufficient.

Below is a snippet of what the error looks like for reference:
![image](https://github.com/user-attachments/assets/e53142b5-d036-45c8-bde4-b306eaea8a89)

**Comment by cjsha** [comment]
I propose we exclude those URLS from local linkchecks, and then we add a flag to the `docfx-utils.ps1` command for remote linkchecks that doesn't exclude those URLS.

**Comment by cjsha** [comment]
Lychee also calls errors on all the `https://github.com/open-ephys/onix1-bonsai-docs/blob/<branchname>/...` links when you make a new branch `branchname` that hasn't been pushed yet and run the linkcheck in that branch.

**Comment by cjsha** [comment]
Cool. I'm worried blanket excluding `open-ephys/bonsai-onix1-docs` might be too broad that we end up excluding URLs we actually do want to check. How about this? We add `--exclude ^https://github\.com/open-ephys/onix1-bonsai-docs/blob/.*/#L1` to the lychee command. For remote linkchecks, the docfx-utils.ps1 command is run with a flag `-r` that runs an alternative lychee command without `--exclude ^https://github\.com/open-ephys/onix1-bonsai-docs/blob/.*/#L1`.
