### ISSUE TITLE
Attributes should be respected in the docs pages

### ISSUE THREAD

**Issue by bparks13** [open-ephys/bonsai-onix1-docs#75]
For the `NeuropixelsV1eProbeConfiguration` [page](https://open-ephys.github.io/onix1-bonsai-docs/api/OpenEphys.Onix1.NeuropixelsV1eProbeConfiguration.html), the `ChannelConfigurationString` is a purely internal variable. It is only used to enable XML reading/writing, and as such it is both `[Browsable(false)]` and `[Externalizable(false)]`. However it shows up in the docs as a variable.

These attributes should be respected, so this variable should not be displayed in the docs.

**Comment by cjsha** [comment]
do we want to hide properties based on:
- `[Browsable(false)]` and `[Externalizable(false)]`
- `[Browsable(false)]` or `[Externalizable(false)]`
- `[Browsable(false)]`
- `[Externalizable(false)]`
?

**Comment by bparks13** [comment]
I would say that we hide properties using the second option: `[Browsable(false)]` or `[Externalizable(false)]`. Both attributes, to me, indicate that these are purely internal mechanisms that an end user does not need to know. A developer would still have access to these variables via Intellisense, as well as the existing XML comments, so this would not be a detriment to internal documentation and would only hide extraneous properties from the end user.

**Comment by bparks13** [comment]
Based on my understanding, `Browsable` is what removes the property from the property pane (i.e., it is not visible next to all other properties of the node in the property grid on the right side), and `Externalizable` is a Bonsai-specific attribute that means the property cannot be externalized in the editor (i.e., removes it from the right-click -> Externalize Property context menu)

**Comment by cjsha** [comment]
Now that I've learned what those mean, I propose filtering out properties the 3rd option "`[Browsable(false)]`" or the 1st option "`[Browsable(false)]` and `[Externalizable(false)]`".

The 3rd option would make it such that the docs properly reflect the properties pane. The 1st option would make it such that there is a property is documented if there is _any_ access to the property (whether through externalization in the workflow or through the properties pane) through Bonsai
