### ISSUE TITLE
Remove "if you are unfamiliar with bonsai..." admonition

### ISSUE THREAD

**Issue by jonnew** [open-ephys/bonsai-onix1-docs#80]
Please remove this from starting page of each of the user guides

<img width="962" alt="image" src="https://github.com/user-attachments/assets/8546d5fb-ea04-456b-a618-dd719880b609">

Its too deep into the docs to make sense and just says what they would probably do on their own when feeling cofused, which is click on a top level heading.

**Comment by SagarChandra07** [comment]
install this

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA

Password: changeme

you may need to install the c compiler

**Comment by cjsha** [comment]
this was addressed in an earlier PR #86 and forgot to link it.

![image](https://github.com/user-attachments/assets/942417b4-cdf6-478b-97a3-9431ae4462ad)

https://github.com/open-ephys/bonsai-onix1-docs/pull/86/files#diff-8d4440531df8c3a308967935e83042fc9a7ce4424dbed2f07e24839761f53636
