### ISSUE TITLE
Unify example workflows

### ISSUE THREAD

**Issue by ChucklesOnGitHub** [open-ephys/bonsai-onix1-docs#84]
- Add Breakout Board node
- Add MemoryData node
- Write hub ConfigDevice Node properties to file

The hs64 tutorial includes all of these, we have to revise np1e and np2e. bb example probably doesn't need these.

**Comment by cjsha** [comment]
The .bonsai file does save properties. However, for reproducibility, imo it would be even more robust if the user could save a file with those properties at the time that the workflow was started that is decoupled from the .bonsai file. Each data acquisition session reproduces the properties that were used during that session. Of course, this wouldn't work once we start taking into account acquisition properties which can be changed while the workflow is running. The first two bullet points in the original post: yes. That third bullet point feels like an item that would belong on a wish list.

**Comment by cjsha** [comment]
Part of resolving this issues is implementing the discussion in #97

**Comment by jonnew** [comment]
Ah, i think i somehow misunderstood @ChucklesOnGitHub's original point. I think all she was saying is that all the workflows should have three common elements:

<img width="358" alt="image" src="https://github.com/user-attachments/assets/03d1d8d0-b845-4de1-aec3-5b6f4fc2a45b">

If that's what she was indicating, then I agree

**Comment by ChucklesOnGitHub** [comment]
Yes Jon, that's what I meant. The picture makes it super clear.
Once we finish the Style Guide, we can revise the example workflows to make sure they are uniform as per those guidelines (workflow sections to include as stated here, standard name of saved data files as stated in #97 , etc).

Cris, I agree that it would be nice "if the user could save a file with those properties at the time that the workflow was started that is decoupled from the .bonsai file.", and that it can be part of the wishlist. In this issue I was only referring to the Timestamp node after the ConfigureHeadstage.

**Comment by cjsha** [comment]
In that case, I unified example workflows in #155, and I made a wishlist issue #160 for "if the user could save a file with those properties at the time that the workflow was started that is decoupled from the .bonsai file" so I can close this one.
