### ISSUE TITLE
Add python load scripts to examples in the Hardware Guide

### ISSUE THREAD

**Issue by ChucklesOnGitHub** [open-ephys/bonsai-onix1-docs#88]
Missing on:
- headstage64 
- NP1.0e
- NP2.0e

**Comment by ChucklesOnGitHub** [comment]
Consider providing real sample data recorded with these headstages and workflows.

**Comment by jonnew** [comment]
That's a good idea.

**Comment by jonnew** [comment]
The latest here is that I'm attempting to do some minimal loading with `SpikeInterface` since this is how data will be processed by users.
