### ISSUE TITLE
Standard data file names in example workflows

### ISSUE THREAD

**Issue by jonnew** [open-ephys/bonsai-onix1-docs#97]
For names of files saved in workflows, follow the example of the workflow in the BreakoutBoard user guide.

**Comment by cjsha** [comment]
> Timestamps are the best for filenames. But they become extremely annoying if there are bunch of files for a single session that get created at different times and therefore have different suffixes. This is going to be common with this library, so we should stay away from them.
>
> It also indicates we need a more unified recording operator, but this is already on the TODO.

_Originally posted by @jonnew in https://github.com/open-ephys/bonsai-onix1-docs/issues/135#issuecomment-2448478601_
            
Part of resolving this issue is mentioning jon's comment in the style guide that ceci and I are maintaining in a branch.

**Comment by cjsha** [comment]
Resolved in #155.
